services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # You’ll add this manually on Render dashboard
